main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('main/', views.main, name='main'),
    path('prescriptions/', views.prescriptions_index, name='index'),
    path('prescriptions/<int:prescription_id>/', views.prescriptions_detail, name='detail'),
    path('prescriptions/create/', views.PrescriptionCreate.as_view(), name='prescriptions_create'),
    path('prescriptions/<int:pk>/update/', views.PrescriptionUpdate.as_view(), name='prescriptions_update'),
    path('prescriptions/<int:pk>/delete/', views.PrescriptionDelete.as_view(), name='prescriptions_delete'),
    path('prescriptions/<int:prescription_id>/add_dosing/', views.add_dosing, name='add_dosing'),
    path('prescriptions/<int:prescription_id>/remove_dosing/<int:dosing_id>/', views.remove_dosing,
         name='remove_dosing'),
    path('prescriptions/<int:prescription_id>/add_note/', views.add_note, name='add_note'),
    path('prescriptions/<int:prescription_id>/remove_note/<int:note_id>/', views.remove_note, name='remove_note'),
    path('accounts/signup/', views.signup, name='signup'),
]

prescription/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date, datetime
from pytz import timezone

from django.contrib.auth.models import User


# Create your models here.
class Prescription(models.Model):
    rx_number = models.IntegerField()
    prescription_issue_date = models.DateField()
    times_per_day = models.IntegerField()
    medicine = models.CharField(max_length=100)
    condition = models.CharField(max_length=100)
    revisit = models.IntegerField()
    tests = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'prescription_id': self.id})

    def taken_today(self):
        return self.dosing_set.filter(date=date.today()).count() >= self.times_per_day

    def times_taken(self):
        # Convert date to Pacific time.
        format = "%Y-%m-%d"
        now_utc = datetime.now(timezone('UTC'))
        now_wc = now_utc.astimezone(timezone('US/Pacific'))

        return self.times_per_day - self.dosing_set.filter(date=now_wc.strftime(format)).count()


class Dosing(models.Model):
    date = models.DateField('Administration Date')
    time = models.TimeField()

    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.date} at {self.time}"

    class Meta:
        ordering = ['-date']


class Note(models.Model):
    date = models.DateField('Note Date')
    content = models.CharField(max_length=250)

    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Dosing, Note


class DosingForm(ModelForm):
    date = forms.DateField(label="Administration Date", widget=forms.TextInput(attrs={'id': 'dose_date'}))

    class Meta:
        model = Dosing
        fields = ['date', 'time']


class NoteForm(ModelForm):
    date = forms.DateField(label="Note Date", widget=forms.TextInput(attrs={'id': 'note_date'}))

    class Meta:
        model = Note
        fields = ['date', 'content']

main_app/views.py
from django.shortcuts import render, redirect

from .models import Prescription, Note, Dosing

# Form import(s)
from .forms import DosingForm, NoteForm

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'django-pillpal-bucket'

# CBV imports
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


def home(request):
    if request.user.is_authenticated:
        return redirect('main')
    else:
        return render(request, 'home.html')


@login_required
def main(request):
    return render(request, 'main.html')


@login_required
def prescriptions_index(request):
    prescriptions = Prescription.objects.filter(user=request.user)

    return render(request, 'prescriptions/index.html',
                  {'prescriptions': prescriptions})


@login_required
def prescriptions_detail(request, prescription_id):
    prescription = Prescription.objects.get(id=prescription_id)
    dosing_form = DosingForm()
    note_form = NoteForm()

    return render(request, 'prescriptions/detail.html',
                  {'prescription': prescription, 'dosing_form': dosing_form, 'note_form': note_form})


@login_required
def add_dosing(request, prescription_id):
    form = DosingForm(request.POST)
    if form.is_valid():
        new_dosing = form.save(commit=False)
        new_dosing.prescription_id = prescription_id
        new_dosing.save()
    return redirect('detail', prescription_id=prescription_id)


@login_required
def remove_dosing(request, prescription_id, dosing_id):
    Dosing.objects.get(id=dosing_id).delete()
    return redirect('detail', prescription_id=prescription_id)


@login_required
def add_note(request, prescription_id):
    form = NoteForm(request.POST)
    if form.is_valid():
        new_note = form.save(commit=False)
        new_note.prescription_id = prescription_id
        new_note.save()
    return redirect('detail', prescription_id=prescription_id)


@login_required
def remove_note(request, prescription_id, note_id):
    Note.objects.get(id=note_id).delete()
    return redirect('detail', prescription_id=prescription_id)


class PrescriptionCreate(LoginRequiredMixin, CreateView):
    model = Prescription
    fields = ['rx_number', 'prescription_issue_date', 'prescription_filled_date', 'times_per_day',
              'delivery', 'dosage', 'refills']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url = '/prescriptions/'


class PrescriptionUpdate(LoginRequiredMixin, UpdateView):
    model = Prescription
    fields = ['rx_number', 'prescription_issue_date', 'prescription_filled_date', 'times_per_day',
              'delivery', 'dosage', 'refills']


class PrescriptionDelete(LoginRequiredMixin, DeleteView):
    model = Prescription
    success_url = '/prescriptions/'


'''
Sign up
'''


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
        else:
            error_message = 'Invalid sign up - try again.'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Prescription</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" integrity="sha512-UJfAaOlIRtdR+0P6C3KUoTDAxVTuy3lnSXLyLKlHYJlcSU8Juge/mjeaxDNMlw9LgeIotgz5FP8eUQPhX1q10A==" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" integrity="sha512-NiWqa2rceHnN3Z5j6mSAvbwwg3tiwVNxiAQaaSMSXnRRDh5C2mk/+sKQRw8qjV1vN4nf8iK2a0b048PnHbyx+Q==" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="navbar-fixed">
      <ul id="dropdown" class="dropdown-content">
        {% if user.is_authenticated %}
          <li><a href="/">Main Page</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'index' %}">View All Prescriptions</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign up</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'login' %}">Log in</a></li>
        {% endif %}
      </ul>

      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">
            <img src="{% static "imgs/pillpal2-sm2.png" %}" id="sm-logo">
          </a>
            <ul class="right">
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown"><i class="material-icons right">menu</i></a></li>
            </ul>
        </div>
      </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    
    <footer class="page-footer">

    </footer>
  
  </body>
</html>

<script> $(".dropdown-trigger").dropdown(); </script>

main_app/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Prescription</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body id="landing-page-bg">
  <main class="container">
    <h1>Prescription</h1>
    <form action="{% url 'signup' %}" method='POST'>
      {% csrf_token %}
      <button class="btn" id="landing-btn" type="submit">Sign up</button>
    </form>

    <form action="{% url 'login' %}" method="POST">
      {% csrf_token %}
      <button class="btn" id="landing-btn" type="submit">Login</button>
    </form>
  </main>
</body>
</html>

main_app/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Prescription</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" integrity="sha512-UJfAaOlIRtdR+0P6C3KUoTDAxVTuy3lnSXLyLKlHYJlcSU8Juge/mjeaxDNMlw9LgeIotgz5FP8eUQPhX1q10A==" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" integrity="sha512-NiWqa2rceHnN3Z5j6mSAvbwwg3tiwVNxiAQaaSMSXnRRDh5C2mk/+sKQRw8qjV1vN4nf8iK2a0b048PnHbyx+Q==" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="navbar-fixed">
      <ul id="dropdown" class="dropdown-content">
        {% if user.is_authenticated %}
          <li><a href="/">Main Page</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'index' %}">View All Prescriptions</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'logout' %}">Log out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign up</a></li>
          <li class="divider"></li>
          <li><a href="{% url 'login' %}">Log in</a></li>
        {% endif %}
      </ul>

      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">
            <img src="{% static "imgs/pillpal2-sm2.png" %}" id="sm-logo">
          </a>
            <ul class="right">
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown"><i class="material-icons right">menu</i></a></li>
            </ul>
        </div>
      </nav>
    </header>

    <main id="main-ctr">
      <div class="main-icons">
        <div class="col">
          <a href="{% url 'index' %}">
            <img src="{% static "imgs/pill-bottle.png" %}" id='pill-bottle'>
          </a>
        </div>
        </div>
      </main>
      
      <footer class="page-footer">

      </footer>
  </body>
</html>

<script> $(".dropdown-trigger").dropdown(); </script>

main_app/templates/main_app/emergencycontact_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Prescription</h1>

  <h4>Are you sure you want to delete your contact?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'ec_detail' %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/emergencycontact_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text"> Contact </span></h1>
  {% else %}
    <h1>Add Emergency Contact</h1>
  {% endif %}

  <div class="card">
    <div class="card-content center-align">
      <form action="" method="POST">
        {% csrf_token %}
        <table>
          {{ form.as_table }}
        </table>
        <div class="card-action">
          <input type="submit" value="Submit" class="btn">
        </div>
      </form>
    </div>
  </div>

{% endblock %}

main_app/templates/main_app/prescription_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Prescription</h1>

  <h4>Are you sure you want to delete <span class="red-text"> Prescription {{object.rx_number}}
  </span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' prescription.id %}" class="btn">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/prescription_form.html
{% extends 'base.html' %}
{% block content %}

  {% if object %}
    <h1>Edit <span class="teal-text"> Prescription {{object.rx_number}}</span></h1>
  {% else %}
    <h1>Add Prescription</h1>
  {% endif %}

  <div class="card">
    <div class="card-content center-align">
      <form action="" method="POST">
        {% csrf_token %}
        <table>
          <!-- {{ form.as_table }} -->
          <tbody>
            <tr>
              <th><label for="id_rx_number">Rx number:</label></th>
              <td>
                <input type="number" name="rx_number" required="" id="id_rx_number" value={{object.rx_number}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_prescription_issue_date">Rx Issue Date:</label></th>
              <td>
                <input type="text" name="prescription_issue_date" required="" id="id_prescription_issue_date" value={{object.prescription_filled_date}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_prescription_filled_date">Rx Filled On Date:</label></th>
              <td>
                <input type="text" name="prescription_filled_date" required="" id="id_prescription_filled_date" value={{object.prescription_filled_date}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_times_per_day">Pills per day:</label></th>
              <td>
                <input type="number" name="times_per_day" required="" id="id_times_per_day" value={{object.times_per_day}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_delivery">Delivery:</label></th>
              <td>
                <input type="text" name="delivery" required="" id="id_delivery" value={{object.delivery}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_dosage">Dosage:</label></th>
              <td>
                <input type="text" name="dosage" required="" id="id_dosage" value={{object.dosage}}>
              </td>
            </tr>
            <tr>
              <th><label for="id_refills">Refills:</label></th>
              <td>
                <input type="number" name="refills" required="" id="id_refills" value={{object.refills}}>
              </td>
            </tr>
          </tbody>
        </table>
        <div class="card-action">
          <input type="submit" value="Submit" class="btn">
        </div>
      </form>
    </div>
  </div>

<script>
  const prescriptionDateEl = document.getElementById("id_prescription_issue_date");
  M.Datepicker.init(prescriptionDateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  const prescriptionFilledDateEl = document.getElementById("id_prescription_filled_date");
  M.Datepicker.init(prescriptionFilledDateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  console.log(this.object)
</script>

{% endblock %}

main_app/templates/prescriptions/detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>Prescription Details</h1>
    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
        <span class="card-title"
        >Prescription {{ prescription.rx_number }}
        </span>
                    <p>Issue Date: {{ prescription.prescription_issue_date }}</p>
                    <p>Condition: {{ prescription.condition }}</p>
                    <p>Take prescribed amount {{ prescription.times_per_day }} times per day</p>
                    <p>Medicine: {{ prescription.medicine }}</p>
                    <p>Tests: {{ prescription.tests }}</p>
                    <p>Revisit (Days): {{ prescription.revisit}}</p>
                </div>
            </div>
            {% for photo in prescription.photo_set.all %}
                <div class="card">
                    <div class="card-image">
                        <img src="{{ photo.url }}">
                    </div>
                    <div class="card-action center-align">
                        <form action="{% url 'remove_photo' prescription.id photo.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn" type="submit">REMOVE
                            </button>
                        </form>
                    </div>
                </div>
            {% empty %}

            {% endfor %}

            {% if not prescription.photo_set.count %}
            {% endif %}
        </div>
        <div class="col s6 center-align">
            <div class="card">
                <div class="card-content">
                    <form action="{% url 'add_dosing' prescription.id %}" method="POST">
                        {% csrf_token %}
                        {{ dosing_form.as_p }}
                </div>
                <div class="card-action">
                    <input type="submit" class="btn" value="Confirm">
                </div>
                </form>
            </div>

            <br/>
            {% if prescription.times_per_day >= prescription.times_taken and prescription.times_taken > 0 %}
                <div class="card-panel amber-text center-align">
                    {% if prescription.times_taken == 1 %}
                        <strong>You have 1 remaining dose </strong>
                    {% else %}
                        <strong>You have {{ prescription.times_taken }} remaining doses</strong>
                    {% endif %}
                </div>
            {% elif prescription.times_taken == 0 %}
                <div class="card-panel teal-text center-align">
                    <strong>You have taken your required doses for today.</strong>
                </div>
            {% else %}
                <div class="card-panel red-text center-align">
                    <strong>You have taken too much today!</strong>
                </div>
            {% endif %}

            <table class="striped">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                </tr>
                </thead>
                <tbody>
                {% for dosing in prescription.dosing_set.all %}
                    <tr>
                        <td>{{ dosing.date }}</td>
                        <td>{{ dosing.time }}</td>
                        <td>
                            <form action="{% url 'remove_dosing' prescription.id dosing.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn" type="submit">
                                    <i class="small material-icons">close</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
            <span class="card-title">Notes</span>
            <table class="striped">
                <thead>
                <tr>
                    <th>Date</th>
                    <th>Note</th>
                </tr>
                </thead>
                {% for note in prescription.note_set.all %}
                    <tbody>
                    <tr>
                        <td>{{ note.date }}</td>
                        <td>{{ note.content }}</td>
                        <td>
                            <form action="{% url 'remove_note' prescription.id note.id %}" method="POST">
                                {% csrf_token %}
                                <button class="btn" type="submit">
                                    <i class="small material-icons">close</i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
            <form action="{% url 'add_note' prescription.id %}" method="POST">
                {% csrf_token %}
                {{ note_form.as_p }}
        </div>
        <div class="card-action center-align">
            <input type="submit" class="btn" value="Add Note">
        </div>
        </form>
    </div>

    <script>
        const doseDateEl = document.getElementById("dose_date");
        M.Datepicker.init(doseDateEl, {
            format: "yyyy-mm-dd",
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true,
        });

        const noteDateEl = document.getElementById("note_date");
        M.Datepicker.init(noteDateEl, {
            format: "yyyy-mm-dd",
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true,
        });

        const timeEl = document.getElementById("id_time");
        const timeInstance = M.Timepicker.init(timeEl, {
            defaultTime: "now",
            twelveHour: false,
            autoClose: true,
        });

        timeInstance._updateTimeFromInput();
        timeInstance.done();
    </script>

{% endblock %}

main_app/templates/prescriptions/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Prescription List</h1>


    {% for prescription in prescriptions %}
        <div class="card">
        <a href="{% url 'detail' prescription.id %}">
        <div class="card-content">
            <span class="card-title">Prescription {{ prescription.rx_number }}</span>
            <p>Date issued: {{ prescription.prescription_issue_date }}</p>
        </div>

    {% endfor %}
{% endblock %}

main_app/templates/search.html
{% extends 'base.html' %}
{% block content %}

<h3>Search by generic name</h3>

<nav>
    <div class="nav-wrapper">
      <form action"" method="POST">
          {% csrf_token %}
        <div class="input-field">
          <input name="search" type="search" placeholder="Search" required>
          <label class="label-icon" for="search"></label>
        </div>
      </form>
    </div>
</nav>
<hr />

{% if medication %}
<div class="row">
    {% for property in medication %}
    <div class="card">
        <div class="card-content">
          <p> <strong> Generic Name: </strong> {{ property.generic_name }} </p>
          <p> <strong> National Drug Code: </strong> {{ property.product_ndc }} </p>
          <p> <strong> Description: </strong> {{ property.packaging.0.description }} </p>
          <p> <strong> Active Ingredient(s): </strong> {% for active_ingredient in property.active_ingredients %}
            <p> {{ active_ingredient.strength }} </p>
            <p> {{ active_ingredient.name }} </p>
            {% endfor %} </p>
        </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

{% endblock %}